version: '3.8'

services:
  backend:
    build:
      context: ./remarcable
      dockerfile: Dockerfile
    volumes:
      - ./remarcable:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./remarcable-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend